title: 'gusutabo.github.io'
url: "https://gusutabo.github.io"

header_pages:
  - index.md

style: nord

footer: 'e-mail: gustavolinssm@gmail.com'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
